Add-Type -AssemblyName 'System.IO.Compression.FileSystem'
$zip = [System.IO.Compression.ZipFile]::Open('C:\Users\madecat\Coding\WO Generator-Claude\minimal_test.zip', [System.IO.Compression.ZipArchiveMode]::Create)
$e = $zip.CreateEntry('solution.xml', [System.IO.Compression.CompressionLevel]::Optimal)
$s = $e.Open()
$b = [System.IO.File]::ReadAllBytes('C:\Users\madecat\Coding\WO Generator-Claude\.sol_minimal\solution.xml')
$s.Write($b, 0, $b.Length)
$s.Dispose()
$e = $zip.CreateEntry('customizations.xml', [System.IO.Compression.CompressionLevel]::Optimal)
$s = $e.Open()
$b = [System.IO.File]::ReadAllBytes('C:\Users\madecat\Coding\WO Generator-Claude\.sol_minimal\customizations.xml')
$s.Write($b, 0, $b.Length)
$s.Dispose()
$e = $zip.CreateEntry('[Content_Types].xml', [System.IO.Compression.CompressionLevel]::Optimal)
$s = $e.Open()
$b = [System.IO.File]::ReadAllBytes('C:\Users\madecat\Coding\WO Generator-Claude\.sol_minimal\[Content_Types].xml')
$s.Write($b, 0, $b.Length)
$s.Dispose()
$e = $zip.CreateEntry('WebResources/mdecat_wogeneratorindexhtml140CD059-BDAA-4582-B3D4-4A56F14500A3', [System.IO.Compression.CompressionLevel]::Optimal)
$s = $e.Open()
$b = [System.IO.File]::ReadAllBytes('C:\Users\madecat\Coding\WO Generator-Claude\.sol_minimal\WebResources\mdecat_wogeneratorindexhtml140CD059-BDAA-4582-B3D4-4A56F14500A3')
$s.Write($b, 0, $b.Length)
$s.Dispose()
$zip.Dispose()
